"""
Keeps frontend/src/test/fixtures/apple_public.json in step with the backend.

The frontend chart and image-export tests run without a backend, against the
JSON the API returns for apple_public.dat. If this test fails, the API output
changed: regenerate the file with

    cd backend && python -m tests.test_frontend_fixture
"""
import json
import os

import api
from pmp_parser import PmpParser

HERE = os.path.dirname(__file__)
SOURCE = os.path.join(HERE, "fixtures", "apple_public.dat")
TARGET = os.path.join(HERE, "..", "..", "frontend", "src", "test", "fixtures",
                      "apple_public.json")


def build() -> dict:
    with open(SOURCE, encoding="utf-8") as fh:
        api._engine = PmpParser.from_dat_text(fh.read()).engine
    gala = api.SubpopRequest(focal_id="Gala", ancestors=True, descendants=True)
    return {
        "_comment": "Generated by backend/tests/test_frontend_fixture.py; do not edit.",
        "pedigree": {k: v for k, v in api.get_pedigree().items() if k != "individuals"},
        "graph": api.get_graph(),
        "subpop_gala": api.build_subpop(gala),
        "color_S1_S2": api.color_by_trait("S1_S2"),
    }


def _dump(data: dict) -> str:
    return json.dumps(data, indent=1, ensure_ascii=False) + "\n"


def test_frontend_fixture_is_current(monkeypatch):
    monkeypatch.setattr(api, "_engine", api._engine)     # restore after build()
    with open(TARGET, encoding="utf-8") as fh:
        assert fh.read() == _dump(build())


if __name__ == "__main__":
    with open(TARGET, "w", encoding="utf-8") as fh:
        fh.write(_dump(build()))
    print(f"wrote {os.path.normpath(TARGET)}")
