"""
Keeps the frontend's test fixtures in step with the backend.

The frontend chart and image-export tests run without a backend, against the
JSON the API returns for apple_public.dat and Example.dat. If this test fails,
the API output changed: regenerate the files with

    cd backend && python -m tests.test_frontend_fixture

When the private TransApple file is present (it is never committed), the same
command also writes its graph to frontend/src/test/fixtures/private/, which is
gitignored, for the frontend tests that run on it locally.
"""
import json
import os

import api
from pmp_parser import PmpParser

HERE = os.path.dirname(__file__)
FIXTURES = os.path.join(HERE, "fixtures")
FRONTEND_FIXTURES = os.path.join(HERE, "..", "..", "frontend", "src", "test", "fixtures")
TARGETS = {
    "apple_public.json": "apple_public.dat",
    "example.json": "Example.dat",
}
PRIVATE_SOURCE = os.path.join(FIXTURES, "TransApple_Consolidated.dat")
PRIVATE_TARGET = os.path.join(FRONTEND_FIXTURES, "private", "transapple.json")
COMMENT = "Generated by backend/tests/test_frontend_fixture.py; do not edit."


def _load(path: str) -> None:
    with open(path, encoding="utf-8") as fh:
        api._engine = PmpParser.from_dat_text(fh.read()).engine


def _pedigree() -> dict:
    return {k: v for k, v in api.get_pedigree().items() if k != "individuals"}


def build(target: str) -> dict:
    _load(os.path.join(FIXTURES, TARGETS[target]))
    if target == "example.json":
        return {"_comment": COMMENT, "pedigree": _pedigree(), "graph": api.get_graph()}
    gala = api.SubpopRequest(focal_id="Gala", ancestors=True, descendants=True)
    return {
        "_comment": COMMENT,
        "pedigree": _pedigree(),
        "graph": api.get_graph(),
        "subpop_gala": api.build_subpop(gala),
        "color_S1_S2": api.color_by_trait("S1_S2"),
    }


def _dump(data: dict) -> str:
    return json.dumps(data, indent=1, ensure_ascii=False) + "\n"


def test_frontend_fixtures_are_current(monkeypatch):
    monkeypatch.setattr(api, "_engine", api._engine)     # restore after build()
    for target in TARGETS:
        with open(os.path.join(FRONTEND_FIXTURES, target), encoding="utf-8") as fh:
            assert fh.read() == _dump(build(target)), f"{target} is out of date"


if __name__ == "__main__":
    for target in TARGETS:
        path = os.path.join(FRONTEND_FIXTURES, target)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(_dump(build(target)))
        print(f"wrote {os.path.normpath(path)}")
    if os.path.exists(PRIVATE_SOURCE):
        _load(PRIVATE_SOURCE)
        os.makedirs(os.path.dirname(PRIVATE_TARGET), exist_ok=True)
        with open(PRIVATE_TARGET, "w", encoding="utf-8") as fh:
            fh.write(json.dumps({"graph": api.get_graph()}, ensure_ascii=False))
        print(f"wrote {os.path.normpath(PRIVATE_TARGET)} (gitignored)")
